/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SunsetPrivateRouteImport } from './routes/sunset-private'
import { Route as SunsetRouteImport } from './routes/sunset'
import { Route as SharkToothHuntRouteImport } from './routes/shark-tooth-hunt'
import { Route as KidsFishingCampRouteImport } from './routes/kids-fishing-camp'
import { Route as FossilHuntRouteImport } from './routes/fossil-hunt'
import { Route as DolphinWatchingRouteImport } from './routes/dolphin-watching'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BachelorettePartyCruiseRouteImport } from './routes/bachelorette-party-cruise'
import { Route as BacheloretteRouteImport } from './routes/bachelorette'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicRezdyProductsRouteImport } from './routes/api/public/rezdy-products'
import { Route as ApiPublicRezdyCreateBookingRouteImport } from './routes/api/public/rezdy-create-booking'
import { Route as ApiPublicRezdyAvailabilityRouteImport } from './routes/api/public/rezdy-availability'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SunsetPrivateRoute = SunsetPrivateRouteImport.update({
  id: '/sunset-private',
  path: '/sunset-private',
  getParentRoute: () => rootRouteImport,
} as any)
const SunsetRoute = SunsetRouteImport.update({
  id: '/sunset',
  path: '/sunset',
  getParentRoute: () => rootRouteImport,
} as any)
const SharkToothHuntRoute = SharkToothHuntRouteImport.update({
  id: '/shark-tooth-hunt',
  path: '/shark-tooth-hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsFishingCampRoute = KidsFishingCampRouteImport.update({
  id: '/kids-fishing-camp',
  path: '/kids-fishing-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const FossilHuntRoute = FossilHuntRouteImport.update({
  id: '/fossil-hunt',
  path: '/fossil-hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const DolphinWatchingRoute = DolphinWatchingRouteImport.update({
  id: '/dolphin-watching',
  path: '/dolphin-watching',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BachelorettePartyCruiseRoute = BachelorettePartyCruiseRouteImport.update({
  id: '/bachelorette-party-cruise',
  path: '/bachelorette-party-cruise',
  getParentRoute: () => rootRouteImport,
} as any)
const BacheloretteRoute = BacheloretteRouteImport.update({
  id: '/bachelorette',
  path: '/bachelorette',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRezdyProductsRoute = ApiPublicRezdyProductsRouteImport.update({
  id: '/api/public/rezdy-products',
  path: '/api/public/rezdy-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRezdyCreateBookingRoute =
  ApiPublicRezdyCreateBookingRouteImport.update({
    id: '/api/public/rezdy-create-booking',
    path: '/api/public/rezdy-create-booking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRezdyAvailabilityRoute =
  ApiPublicRezdyAvailabilityRouteImport.update({
    id: '/api/public/rezdy-availability',
    path: '/api/public/rezdy-availability',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bachelorette': typeof BacheloretteRoute
  '/bachelorette-party-cruise': typeof BachelorettePartyCruiseRoute
  '/contact': typeof ContactRoute
  '/dolphin-watching': typeof DolphinWatchingRoute
  '/fossil-hunt': typeof FossilHuntRoute
  '/kids-fishing-camp': typeof KidsFishingCampRoute
  '/shark-tooth-hunt': typeof SharkToothHuntRoute
  '/sunset': typeof SunsetRoute
  '/sunset-private': typeof SunsetPrivateRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/rezdy-availability': typeof ApiPublicRezdyAvailabilityRoute
  '/api/public/rezdy-create-booking': typeof ApiPublicRezdyCreateBookingRoute
  '/api/public/rezdy-products': typeof ApiPublicRezdyProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bachelorette': typeof BacheloretteRoute
  '/bachelorette-party-cruise': typeof BachelorettePartyCruiseRoute
  '/contact': typeof ContactRoute
  '/dolphin-watching': typeof DolphinWatchingRoute
  '/fossil-hunt': typeof FossilHuntRoute
  '/kids-fishing-camp': typeof KidsFishingCampRoute
  '/shark-tooth-hunt': typeof SharkToothHuntRoute
  '/sunset': typeof SunsetRoute
  '/sunset-private': typeof SunsetPrivateRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/rezdy-availability': typeof ApiPublicRezdyAvailabilityRoute
  '/api/public/rezdy-create-booking': typeof ApiPublicRezdyCreateBookingRoute
  '/api/public/rezdy-products': typeof ApiPublicRezdyProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bachelorette': typeof BacheloretteRoute
  '/bachelorette-party-cruise': typeof BachelorettePartyCruiseRoute
  '/contact': typeof ContactRoute
  '/dolphin-watching': typeof DolphinWatchingRoute
  '/fossil-hunt': typeof FossilHuntRoute
  '/kids-fishing-camp': typeof KidsFishingCampRoute
  '/shark-tooth-hunt': typeof SharkToothHuntRoute
  '/sunset': typeof SunsetRoute
  '/sunset-private': typeof SunsetPrivateRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/rezdy-availability': typeof ApiPublicRezdyAvailabilityRoute
  '/api/public/rezdy-create-booking': typeof ApiPublicRezdyCreateBookingRoute
  '/api/public/rezdy-products': typeof ApiPublicRezdyProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bachelorette'
    | '/bachelorette-party-cruise'
    | '/contact'
    | '/dolphin-watching'
    | '/fossil-hunt'
    | '/kids-fishing-camp'
    | '/shark-tooth-hunt'
    | '/sunset'
    | '/sunset-private'
    | '/terms'
    | '/api/chat'
    | '/api/public/rezdy-availability'
    | '/api/public/rezdy-create-booking'
    | '/api/public/rezdy-products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bachelorette'
    | '/bachelorette-party-cruise'
    | '/contact'
    | '/dolphin-watching'
    | '/fossil-hunt'
    | '/kids-fishing-camp'
    | '/shark-tooth-hunt'
    | '/sunset'
    | '/sunset-private'
    | '/terms'
    | '/api/chat'
    | '/api/public/rezdy-availability'
    | '/api/public/rezdy-create-booking'
    | '/api/public/rezdy-products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bachelorette'
    | '/bachelorette-party-cruise'
    | '/contact'
    | '/dolphin-watching'
    | '/fossil-hunt'
    | '/kids-fishing-camp'
    | '/shark-tooth-hunt'
    | '/sunset'
    | '/sunset-private'
    | '/terms'
    | '/api/chat'
    | '/api/public/rezdy-availability'
    | '/api/public/rezdy-create-booking'
    | '/api/public/rezdy-products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacheloretteRoute: typeof BacheloretteRoute
  BachelorettePartyCruiseRoute: typeof BachelorettePartyCruiseRoute
  ContactRoute: typeof ContactRoute
  DolphinWatchingRoute: typeof DolphinWatchingRoute
  FossilHuntRoute: typeof FossilHuntRoute
  KidsFishingCampRoute: typeof KidsFishingCampRoute
  SharkToothHuntRoute: typeof SharkToothHuntRoute
  SunsetRoute: typeof SunsetRoute
  SunsetPrivateRoute: typeof SunsetPrivateRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicRezdyAvailabilityRoute: typeof ApiPublicRezdyAvailabilityRoute
  ApiPublicRezdyCreateBookingRoute: typeof ApiPublicRezdyCreateBookingRoute
  ApiPublicRezdyProductsRoute: typeof ApiPublicRezdyProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunset-private': {
      id: '/sunset-private'
      path: '/sunset-private'
      fullPath: '/sunset-private'
      preLoaderRoute: typeof SunsetPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunset': {
      id: '/sunset'
      path: '/sunset'
      fullPath: '/sunset'
      preLoaderRoute: typeof SunsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shark-tooth-hunt': {
      id: '/shark-tooth-hunt'
      path: '/shark-tooth-hunt'
      fullPath: '/shark-tooth-hunt'
      preLoaderRoute: typeof SharkToothHuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-fishing-camp': {
      id: '/kids-fishing-camp'
      path: '/kids-fishing-camp'
      fullPath: '/kids-fishing-camp'
      preLoaderRoute: typeof KidsFishingCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fossil-hunt': {
      id: '/fossil-hunt'
      path: '/fossil-hunt'
      fullPath: '/fossil-hunt'
      preLoaderRoute: typeof FossilHuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dolphin-watching': {
      id: '/dolphin-watching'
      path: '/dolphin-watching'
      fullPath: '/dolphin-watching'
      preLoaderRoute: typeof DolphinWatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bachelorette-party-cruise': {
      id: '/bachelorette-party-cruise'
      path: '/bachelorette-party-cruise'
      fullPath: '/bachelorette-party-cruise'
      preLoaderRoute: typeof BachelorettePartyCruiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bachelorette': {
      id: '/bachelorette'
      path: '/bachelorette'
      fullPath: '/bachelorette'
      preLoaderRoute: typeof BacheloretteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rezdy-products': {
      id: '/api/public/rezdy-products'
      path: '/api/public/rezdy-products'
      fullPath: '/api/public/rezdy-products'
      preLoaderRoute: typeof ApiPublicRezdyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rezdy-create-booking': {
      id: '/api/public/rezdy-create-booking'
      path: '/api/public/rezdy-create-booking'
      fullPath: '/api/public/rezdy-create-booking'
      preLoaderRoute: typeof ApiPublicRezdyCreateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rezdy-availability': {
      id: '/api/public/rezdy-availability'
      path: '/api/public/rezdy-availability'
      fullPath: '/api/public/rezdy-availability'
      preLoaderRoute: typeof ApiPublicRezdyAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacheloretteRoute: BacheloretteRoute,
  BachelorettePartyCruiseRoute: BachelorettePartyCruiseRoute,
  ContactRoute: ContactRoute,
  DolphinWatchingRoute: DolphinWatchingRoute,
  FossilHuntRoute: FossilHuntRoute,
  KidsFishingCampRoute: KidsFishingCampRoute,
  SharkToothHuntRoute: SharkToothHuntRoute,
  SunsetRoute: SunsetRoute,
  SunsetPrivateRoute: SunsetPrivateRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicRezdyAvailabilityRoute: ApiPublicRezdyAvailabilityRoute,
  ApiPublicRezdyCreateBookingRoute: ApiPublicRezdyCreateBookingRoute,
  ApiPublicRezdyProductsRoute: ApiPublicRezdyProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
